### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by patrick-mc** [wjdgustn/hyonsubot-webstore#1]
the site does not support mobile.
Please make it reactive so that mobile users can use it easily.

**Comment by wjdgustn** [comment]
Added mobile mainpage.

**Comment by wjdgustn** [comment]
Added mobile profile, cart, history.

**Comment by patrick-mc** [comment]
Working well. Closing issue

**Comment by patrick-mc** [comment]
Administrative page does not work well in mobile

**Comment by wjdgustn** [comment]
Added mobile manage page.
Close issue.
