### ISSUE TITLE
Enable Travis-CI for continuous integration

### ISSUE THREAD

**Issue by patrick-mc** [wjdgustn/hyonsubot-webstore#5]
Requesting a travis ci feature to be enabled.
Related pull requset: #4 

Before making a pull request, please install a travis-ci system through marketplace, or adding this repository to [Travis CI](https://travis-ci.org)

**Comment by patrick-mc** [comment]
you can find marketplace [here](https://github.com/marketplace/travis-ci)

**Comment by wjdgustn** [comment]
I don't have any plans to use travis yet.
